name: Create Project Milestones

on:
  push:
    paths:
      - '.github/workflows/milestones.yml'
  workflow_dispatch:

jobs:
  create-milestones:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Debug Logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Create Milestone for Project Initialization
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/milestones \
          -d '{"title": "Project Initialization", "state": "open", "description": "Foundation layer - Initializing the project."}'

      - name: Create Milestone for Core Feature Development
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/milestones \
          -d '{"title": "Core Feature Development", "state": "open", "description": "Core layer - Developing essential features."}'

      - name: Create Milestone for Proof of Concept
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/milestones \
          -d '{"title": "Proof of Concept", "state": "open", "description": "Validation layer - Creating a proof of concept to validate the core idea."}'